### ISSUE TITLE
How do I use these?

### ISSUE THREAD

**Issue by MKletz** [dsccommunity/DscResource.AnalyzerRules#10]
Is it possible to get some documentation made on how to use these rules? Providing DscResource.AnalyzerRules.psm1 to the customrules path on Invoke-ScriptAnaylzer just throws exceptions

**Comment by PlagueHO** [comment]
Hi @MKletz - a good point/question. But briefly, modules that are converted to the [new CD structure](https://dsccommunity.org/blog/convert-a-module-for-continuous-delivery/) (for example, SQLServerDsc, NetworkingDsc, ComputerManagementDsc and many more) can use this module automatically - with VS Code syntax highlighting and during automated testing.

You need to have run:
```powershell
.\build.ps1 -ResolveDependency -Tasks noop
```

in the repository on your machine to install this module into '.\output\RequiredModules\DscResource.AnalyzerRules' folder where it will be picked up by the `.vscode\analyzersettings.psd1`.

Running (after you've run the -ResolveDependency above):
```powershell
.\build.ps1 -Tasks hqrmtest
```

Will validate the rules against your source code (iirc)? However, you can only run this test on any repositories that have opted in to HQRM guidelines.

**Comment by johlju** [comment]
It is possible to use these in VS Code if you add these to the settings.

**Comment by johlju** [comment]
Closing this as there has been no more comments for a long time.

**Comment by johlju** [comment]
Re-opening this as this should be documented. Closed it to quickly due to the previous 'question' tag.
