### ISSUE TITLE
Measure-Keyword logic error

### ISSUE THREAD

**Issue by Sudman1** [dsccommunity/DscResource.AnalyzerRules#11]
When using a class constructor such as `SqlSetupBase() : base ()`,  script analyzer provides an error stating that keywords must have a space immediately afterwards if followed by parentheses.

In this case, the keyword `base` already has the space character in place. The logic has errantly flagged the ending substring "Base" in `SqlSetupBase` as a keyword. 

To accomodate this issue - and because it can actually be used to form a constructor - I suggest that we put in an exception for the `base` keyword in the `Measure-Keyword` rule.

**Comment by dan-hughes** [comment]
@johlju, what's the correct format for the example class constructor provided here?

**Comment by dan-hughes** [comment]
The format in SqlAudit makes sense from a consistency perspective.

This likely needs to be, check the constructor has a space afterwards if followed by parentheses.

This is still a bug as any constructor with base in it's name is captured.
