### ISSUE TITLE
Rename default branch to Main

### ISSUE THREAD

**Issue by dan-hughes** [dsccommunity/DscResource.AnalyzerRules#22]
Rename the default branch from master to main.

Someone with the correct rights across Github, ADO is required.

**Comment by johlju** [comment]
Yep, saw that it was needed the other day. I will look into it.

**Comment by johlju** [comment]
How to rename default branch is here (so I have a quick access): https://dsccommunity.org/blog/convert-master-to-main/

**Comment by johlju** [comment]
This has been resolved. Default branch is not main.
